### PR TITLE
Added me!

### PR DESCRIPTION
**Pull request by eltfshr**
Hello. My id is 63070501035. 👌

### CODE REVIEW

**Comment by riflowth** [comment]
@eltfshr Welcome to our union!!

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB05T8Uw5LC6W9nrF1g7XEWb0eoP-hnrwdLw&usqp=CAU

**Comment by riflowth** [comment]
Welcome @eltfshr to our union!!!

**Comment by eltfshr** [comment]
I am a third year student in computer engineering(regular program).
I love 🍭 but I hate 🍉🍭.

**Comment by riflowth** [comment]
> I am a third year student in computer engineering(regular program). I love 🍭 but I hate 🍉🍭.

## Melon lover 🍈

**Pull request merged**
