### PR TITLE
🙋

### PR DESCRIPTION
**Pull request by Th1nkK1D**
## Introduce yourself
Lookkid CPE29 krub
58070503429

Nice to meet you all!

### CODE REVIEW

**Comment by Porama6400** [comment]
🇺🇸🇺🇸 god bless America 🇺🇸🇺🇸🔫

**Comment by riflowth** [comment]
### OMG **P'Lookkid** is here 🌠

**Welcome, alumni to our CPE KMUTT Student Union krub** 🌟

**Comment by riflowth** [comment]
### OMG **P'Lookkid** @Th1nkK1D  is here 🌠

**Welcome, alumni to our CPE KMUTT Student Union krub** 🌟

**Comment by wit03** [comment]
FC P'Lookkid Krub

**Comment by Th1nkK1D** [comment]
Keep calm krub. I'm so nervous when I see all of your student numbers. 🤣 65 omg

**Pull request merged**
